spring:
  application:
    name: demo
  #数据库相关配置
  datasource:
    url: jdbc:mysql://47.93.236.82:3306/testdb?useUnicode=true&amp;characterEncoding=utf-8
    username: root
    password: hubiao
    driver-class-name: com.mysql.jdbc.Driver
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
#服务端口
server:
  port: 8080
#mybatis相关配置
mybatis:
  #type-aliases-package: com.fc.model
  mapper-locations: classpath:mapper/*.xml
  config-location: classpath:mybatis-config.xml

